// src/components/AddProductForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-6">
    <div>
      <label class="block text-sm font-medium text-gray-700">Nome do Produto</label>
      <input
        type="text"
        v-model="formData.name"
        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
        required
      />
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700">Descrição</label>
      <textarea
        v-model="formData.description"
        rows="3"
        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
      ></textarea>
    </div>

    <!-- Seção de Classificação Automática -->
    <div v-if="classification" class="bg-blue-50 p-4 rounded-md mb-4">
      <h3 class="text-sm font-medium text-blue-900 mb-2">Classificação Automática</h3>
      <div class="space-y-2">
        <div class="flex items-center">
          <span class="text-sm font-medium text-blue-800">Categoria Sugerida:</span>
          <span class="ml-2 text-sm text-blue-700">
            {{ getCategoryName(classification.categoryId) }}
          </span>
          <span class="ml-2 px-2 py-1 bg-blue-100 text-blue-800 rounded-full text-xs">
            {{ Math.round(classification.confidence * 100) }}% de confiança
          </span>
        </div>
        
        <div v-if="classification.suggestedCategories?.length > 1" class="mt-2">
          <p class="text-xs text-blue-700">Outras sugestões:</p>
          <ul class="mt-1 space-y-1">
            <li 
              v-for="cat in classification.suggestedCategories.slice(1, 3)" 
              :key="cat.id" 
              class="text-xs text-blue-600"
            >
              {{ getCategoryName(cat.id) }} ({{ Math.round(cat.confidence * 100) }}%)
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700">Características (separadas por vírgula)</label>
      <input
        type="text"
        v-model="formData.characteristics"
        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
      />
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700">Preço</label>
      <input
        type="number"
        v-model="formData.price"
        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
        required
      />
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700">Quantidade</label>
      <input
        type="number"
        v-model="formData.quantity"
        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
        required
      />
    </div>

    <div class="flex justify-end">
      <button
        type="submit"
        class="inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
      >
        Adicionar Produto
      </button>
    </div>
  </form>
</template>

<script setup>
import { ref, watch, computed } from 'vue';
import { classifyNewProduct, getCategoryName } from '../utils/productClassification';

const formData = ref({
  name: '',
  description: '',
  characteristics: '',
  price: '',
  quantity: '',
});

const classification = ref(null);

// Observar mudanças nos campos de nome e descrição
watch(
  () => [formData.value.name, formData.value.description, formData.value.characteristics],
  ([name, description, characteristics]) => {
    console.log('Watch ativado:', { name, description, characteristics });
    
    if (name || description) {
      try {
        const result = classifyNewProduct({
          name,
          description,
          characteristics: characteristics 
            ? characteristics.split(',').map(c => c.trim()) 
            : []
        });
        
        console.log('Resultado da classificação:', result);
        classification.value = result;
      } catch (error) {
        console.error('Erro na classificação:', error);
        classification.value = null;
      }
    }
  },
  { immediate: true }
);

const emit = defineEmits(['submit']);

const handleSubmit = () => {
  emit('submit', {
    ...formData.value,
    categoryId: classification.value?.categoryId,
    categoryConfidence: classification.value?.confidence
  });
};
</script>

// src/components/AddProductForm.tsx
import React, { useState, useEffect } from 'react';
import { classifyNewProduct, getCategoryName } from '../utils/productClassification';

interface AddProductFormProps {
  onSubmit: (product: any) => void;
}

export function AddProductForm({ onSubmit }: AddProductFormProps) {
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    characteristics: '',
    price: '',
    quantity: '',
  });

  const [classification, setClassification] = useState<{
    categoryId: string;
    confidence: number;
    suggestedCategories: Array<{ id: string; confidence: number }>;
  } | null>(null);

  // Atualizar classificação quando o nome ou descrição mudar
  useEffect(() => {
    if (formData.name || formData.description) {
      const result = classifyNewProduct({
        name: formData.name,
        description: formData.description,
        characteristics: formData.characteristics.split(',').map(c => c.trim())
      });
      setClassification(result);
    }
  }, [formData.name, formData.description, formData.characteristics]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit({
      ...formData,
      categoryId: classification?.categoryId,
      categoryConfidence: classification?.confidence
    });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <label className="block text-sm font-medium text-gray-700">
          Nome do Produto
        </label>
        <input
          type="text"
          name="name"
          value={formData.name}
          onChange={handleChange}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          required
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700">
          Descrição
        </label>
        <textarea
          name="description"
          value={formData.description}
          onChange={handleChange}
          rows={3}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700">
          Características (separadas por vírgula)
        </label>
        <input
          type="text"
          name="characteristics"
          value={formData.characteristics}
          onChange={handleChange}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700">
          Preço
        </label>
        <input
          type="number"
          name="price"
          value={formData.price}
          onChange={handleChange}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          required
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700">
          Quantidade
        </label>
        <input
          type="number"
          name="quantity"
          value={formData.quantity}
          onChange={handleChange}
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          required
        />
      </div>

      {classification && (
        <div className="bg-gray-50 p-4 rounded-md">
          <h3 className="text-sm font-medium text-gray-900">
            Classificação Sugerida
          </h3>
          <div className="mt-2 space-y-2">
            <p className="text-sm text-gray-600">
              Categoria Principal: {getCategoryName(classification.categoryId)}
              <span className="ml-2 text-xs text-gray-500">
                ({Math.round(classification.confidence * 100)}% de confiança)
              </span>
            </p>
            {classification.suggestedCategories.length > 1 && (
              <div>
                <p className="text-xs text-gray-500 mt-1">Outras sugestões:</p>
                <ul className="text-xs text-gray-500">
                  {classification.suggestedCategories.slice(1, 3).map(cat => (
                    <li key={cat.id}>
                      {getCategoryName(cat.id)} ({Math.round(cat.confidence * 100)}%)
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}

      <div className="flex justify-end">
        <button
          type="submit"
          className="inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
        >
          Adicionar Produto
        </button>
      </div>
    </form>
  );
}
